---
sudo: false
language: ruby
cache: bundler
before_install: gem install bundler
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - jruby

jobs:
  include:
    rvm: 2.5
    name: 'Ruby: 3.0.0.preview1'
    before_install: rvm get head && rvm use --install --binary 3.0.0.preview1
    cache: bundler
