[package]
name = "fast_ignore"
version = "0.4.1"
authors = ["Dana Sherson <robot@dana.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
helix = "0.7.5"
ignore = "0.4.10"
